# action.yml
name: 'Project Catalyst Pre-built tooling Build Action'
description: 'Use pre-built tools to spee upd and simplify CI'
inputs:
  tool-cmd:  # id of input
    description: 'The command to run'
    required: false
    default: 'mdbook build'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tool-cmd }}
branding:
  icon: 'settings'
  color: 'purple'
